// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYvZe0ph-P6qsHYgC4cx2MXVcBz5GOHH0',
    appId: '1:972576225676:web:457e54d0c13af91bdf7ea9',
    messagingSenderId: '972576225676',
    projectId: 'login-flutter-1bc19',
    authDomain: 'login-flutter-1bc19.firebaseapp.com',
    storageBucket: 'login-flutter-1bc19.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Pm21OnlMerAhCVpv98VhtuAM-8YeHDU',
    appId: '1:972576225676:android:864fd0b0e1412c67df7ea9',
    messagingSenderId: '972576225676',
    projectId: 'login-flutter-1bc19',
    storageBucket: 'login-flutter-1bc19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArwxB-oNJW9UlmXRbLmy2Z2YXma0n-l98',
    appId: '1:972576225676:ios:28aa683b5e511a5bdf7ea9',
    messagingSenderId: '972576225676',
    projectId: 'login-flutter-1bc19',
    storageBucket: 'login-flutter-1bc19.appspot.com',
    iosClientId: '972576225676-ncq9ae805u6p2p5c8bua79gn8m3pkod1.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocFlutterLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArwxB-oNJW9UlmXRbLmy2Z2YXma0n-l98',
    appId: '1:972576225676:ios:28aa683b5e511a5bdf7ea9',
    messagingSenderId: '972576225676',
    projectId: 'login-flutter-1bc19',
    storageBucket: 'login-flutter-1bc19.appspot.com',
    iosClientId: '972576225676-ncq9ae805u6p2p5c8bua79gn8m3pkod1.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocFlutterLogin',
  );
}
